### ISSUE TITLE
When displaying a single level map, I am unable to pan 

### ISSUE THREAD

**Issue by nachtien** [peterLaurence/MapCompose#38]
I'm loving this library :). Great work on it! 

I am unable to pan to the bottom/top of the image when I'm zoomed in. 
Another thing I noticed: When zoomed out, you'll see that the image isn't centered in the screen, it's shifted towards the bottom.
Annndd one more: Is there anyway I can remove the flicker when zooming in/out quickly?

Source code:
```kotlin
val width = 5000
val height = 3712
val state: MapState by remember { // TODO: Put this in a view model
mutableStateOf(
	MapState(1, width, height, width).apply {
		addLayer(tileStreamProvider = provider)
	}
  )
}
MapUI(state = state)
```

**Comment by peterLaurence** [comment]
This is because you're using the library to display one single big image, something the library wasn't designed for.
You need to first tile the big image using `vips dzsave` (you've done that before).
MapCompose only supports square tiles (which `vips dzsave` produces). That explains why you can't properly navigate in this single rectangular tile.
I would advise you to use MapCompose `1.1.1` (and use Compose `1.0.5`) for now, as Compose 1.1.0 isn't particularly stable yet.

**Comment by nachtien** [comment]
ahh yeah, we're waiting for our devs to build that part out but it might be some time so that's why I'm loading one big image.  Thanks for the quick feedback. 👍 

Maybe I'll include `vips` and create native bindings.

**Comment by peterLaurence** [comment]
If you plan to bundle tiles in your apk, the simplest way is to create tiles from a development machine, and then import then as Android resources. 
If you can't pro-process images and have them tiled on the fly, then this can be done by a server, which then serves tiles through HTTP.

**Comment by nachtien** [comment]
Since our server is only giving us png, and currently our backend devs have other priorities, so the only option I have is to create the image pyramid on the Android device at the moment in order to use MapCompose. 

The dev before me implemented [Subsample Scale Image View](https://github.com/davemorrissey/subsampling-scale-image-view/), but the logic to do what we want is much easier with your library. Maybe i could check out what they do for tiling and implement that in the `tileStreamProvider`?

**Comment by peterLaurence** [comment]
> Maybe i could check out what they do for tiling

Yes, and extract that logic so you can pre-process your images and write tiles into a local directory (on the device). Your implementation of `TileStreamProvider` will then just tap into the tiles files.

It's probably the easiest way to go, since I'm not even sure can can compile `libvips` using the Android NDK. You're lucky that "Subsampling Scale Image View" is open source ;)

**Comment by nachtien** [comment]
Thanks for your help. I'll close this ticket :)
