### ISSUE TITLE
Tile borders are visible

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#5]
Here is a map displaying fully blue tiles:

![image](https://user-images.githubusercontent.com/11064768/142762382-7e07f55e-e9bd-44a2-bf32-c51cb0f32c32.png)

The expected outcome would be just a blue image, but instead the tiles are clearly visible.

**Comment by peterLaurence** [comment]
This one is nasty, and a bit embarrassing.
Though I managed to fix it, I need to be sure of the changes.

**Comment by Nohus** [comment]
This issue is still present. The fix seemed to have helped, the lines are now less common and are even completely gone at specific zoom levels, but are otherwise still very much visible.

**Comment by peterLaurence** [comment]
Turns out, tile placement was originally right.
It seems like an undesirable effect of the api used to place tiles on the canvas. To test that, I have drawn on the canvas squares of the same size and at the same positions of tiles. The result is a smooth concatenation of the squares (no borders).

Which makes me think that there might be an issue upstream, with the `DrawScope.drawImage` API. A good thing is (if I'm right) that should be easy to reproduce outside of this library.
Meanwhile, I'm reverting my changes.

**Comment by Nohus** [comment]
What is the outlook on fixing this then? :thinking:

**Comment by Nohus** [comment]
Fixed on master.
