### ISSUE TITLE
Cannot scrollTo fully zoomed out map

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#7]
I would like to scroll the map to the center, zoomed out as far as possible. My `minScaleMode` is set `Fill`. I cannot do it, because `minScale` is not exposed publicly (contrary to `maxScale`) and so I cannot retrieve it to know what is the target scale I need.

I expected `scrollTo(0.5, 0.5, 0f)` to work, but it does not: the map correctly zooms out as far as possible, but does not move to the center. It seems the animation is stopped as soon as it hits `minScale` because it cannot animate the scale any further, even though it still hasn't scrolled to the target position.

Either making `scrollTo` clamp the provided scale or exposing `minScale` with a public getter would solve this issue.

---

Sorry for opening all the issues: The library is amazing and the only one that actually worked properly for my use case after trying a few others. And it using Compose is an additional bonus. Thank you!

**Comment by peterLaurence** [comment]
I could reproduce, thanks for reporting this.

**Comment by peterLaurence** [comment]
That's because the minimum scale depends on the actual size of the map on screen (among other things). The map needs to be laid out before the minimum scale can be known.
This can be solved, by suspending until the first layout pass. However, the downsize is we can't have a nice property access -- we need a suspending function.

Adding the following API
```
suspend fun MapState.getMinScale(): Float {
    with(zoomPanRotateState) {
        awaitLayout()
        return zoomPanRotateState.minScale
    }
}
```

With the following usage :
```
val state: MapState by mutableStateOf(
        MapState(4, 4096, 4096, tileStreamProvider).apply {
            shouldLoopScale = true
            minimumScaleMode = Fill
            viewModelScope.launch {
                val minScale = getMinScale()
                scrollTo(0.5, 0.5, minScale)
                scale = 0f
            }
        }
    )
```

That works.
But I wonder if we really need that new API. Instead, `scrollTo` should probably be fixed to have `scrollTo(0.5, 0.5, 0f)` produce the expected result.

**Comment by Nohus** [comment]
`scrollTo(0.5, 0.5, 0f)` could clamp the `0f` up to the actual `minScale` value if known, and suspend if first layout hasn't happened yet (which it already does anyway).

**Comment by peterLaurence** [comment]
I've just made a fix to `scrollTo` API. Now, `scrollTo(0.5, 0.5, 0f)` should work. Can you confirm?

**Comment by Nohus** [comment]
I'll try to compile it locally and test.

**Comment by Nohus** [comment]
Can confirm it works now, thank you!
