### ISSUE TITLE
[Feature Request] Suspending version of TileStreamProvider

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#8]
Because `getTileStream()` in the `TileStreamProvider` is not suspending, I need to use `runBlocking` to use my suspending implementation, even though in the library, `getTileStream()` is called from a suspending context anyway:

```Kotlin
tileStreamProvider = { y, x, zoom ->
    runBlocking {
        getMapTile(y, x, zoom)
    }
}
```

It would be nice to be able to provide a suspending implementation directly, without having to use `runBlocking`. This is very minor but would make the interface a bit nicer in my opinion.

**Comment by peterLaurence** [comment]
Fun fact, I initially had a suspending `TileStreamProvider`, which I later removed for the following reason:

It forced to supply a suspending function, when a blocking call just works by design. It gives the false impression that the library needs a non-blocking function.
 
But with kotlin 1.6, we can supply a regular function when a suspending function is expected. Ironic isn't it? 
So yes, I should do that.
